### ISSUE TITLE
Error: Invalid token specified

### ISSUE THREAD

**Issue by gasgithub** [IBM/satellite-config-upload-action#10]
When I try this action with following config:

```
jobs:
  push-sat-config:
    runs-on: ubuntu-latest
    steps:
    # Checkout repo   
    - name: Checkout
      uses: actions/checkout@v2    
    # Create new version
    - name: Update Sat Config
      uses: IBM/satellite-config-actions@v1
      with:
        apikey: '${IBM_CLOUD_API_KEY}'
        filename: 'manifests/guestbook-deployment.yaml'
        channel_id: '${SAT_CHANNEL_UUID}'
        version_name: 'guestbook-v${GITHUB_SHA}'
```
It fails with the following message:
```
Signing in to IBM Cloud
Uploading manifests/guestbook-deployment.yaml to channel ${SAT_CHANNEL_UUID} as version guestbook-v${GITHUB_SHA}
Error: Invalid token specified
```

Any way to provide some debugging params to get better details what the problem is?
